### ISSUE TITLE
Issue running riot with package extras on zsh

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/riot#148]
https://github.com/DataDog/dd-trace-py/blob/bce68ed584d2c3e4e6607a4f8da632c0ea72760a/riotfile.py#L155-L166

```python
        Venv(
            name="docs",
            pys=["3"],
            pkgs={
                "cython": latest,
                "reno[sphinx]": latest,
                "sphinx": latest,
                "sphinxcontrib-spelling": latest,
                "PyEnchant": latest,
            },
            command="scripts/build-docs",
        ),
```

```
❯ riot -v run docs
INFO:riot.riot:Generating virtual environments for interpreters Interpreter(_hint='3')
INFO:riot.riot:Skipping creation of virtualenv '/Users/brett.langdon/datadog/dd-trace-py/.riot/venv_py394' as it already exists.
INFO:riot.riot:Installing dev package.
INFO:riot.riot:Running with Interpreter(_hint='3')
INFO:riot.riot:Creating virtualenv '/Users/brett.langdon/datadog/dd-trace-py/.riot/venv_py394_cython_reno[sphinx]_sphinx_sphinxcontrib-spelling_PyEnchant' with interpreter '/Users/brett.langdon/.pyenv/versions/3.9.4/bin/python3'.
INFO:riot.riot:Installing venv dependencies 'cython' 'reno[sphinx]' 'sphinx' 'sphinxcontrib-spelling' 'PyEnchant' in prefix /Users/brett.langdon/datadog/dd-trace-py/.riot/venv_py394_cython_reno[sphinx]_sphinx_sphinxcontrib-spelling_PyEnchant.
zsh:1: no matches found: /Users/brett.langdon/datadog/dd-trace-py/.riot/venv_py394_cython_reno[sphinx]_sphinx_sphinxcontrib-spelling_PyEnchant/bin/activate
Traceback (most recent call last):
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/riot.py", line 395, in prepare
    Session.run_cmd_venv(
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/riot.py", line 748, in run_cmd_venv
    return run_cmd(cmd, stdout=stdout, executable=executable, env=env, shell=True)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/riot.py", line 810, in run_cmd
    raise CmdFailure("Command %s failed with code %s." % (args[0], r.returncode), r)
riot.riot.CmdFailure: (CmdFailure(...), 'Command s failed with code 1.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/bin/riot", line 5, in <module>
    from riot.__main__ import main
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/__main__.py", line 3, in <module>
    main(auto_envvar_prefix="RIOT")
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/cli.py", line 131, in run
    ctx.obj["session"].run(
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/riot.py", line 548, in run
    inst.prepare(env)
  File "/Users/brett.langdon/.pyenv/versions/3.9.4/lib/python3.9/site-packages/riot/riot.py", line 401, in prepare
    raise CmdFailure(
riot.riot.CmdFailure: (CmdFailure(...), "Failed to install venv dependencies 'cython' 'reno[sphinx]' 'sphinx' 'sphinxcontrib-spelling' 'PyEnchant'\n")
```

**Comment by Kyle-Verhoog** [comment]
Seeing this too now - going to take a stab at fixing it

**Comment by Kyle-Verhoog** [comment]
I think this is due to the use of square brackets in the directory name
