### ISSUE TITLE
psycopg2 failed to install in riot shell

### ISSUE THREAD

**Issue by mabdinur** [DataDog/riot#159]
```
⠙ Preparing shell virtual environment    ERROR: Command errored out with exit status 1:
     command: /root/project/.riot/venv_py3100/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1tqfulpq/psycopg2_335d2db4abf446faad8c7d44979713fb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1tqfulpq/psycopg2_335d2db4abf446faad8c7d44979713fb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-08krewox
         cwd: /tmp/pip-install-1tqfulpq/psycopg2_335d2db4abf446faad8c7d44979713fb/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-08krewox/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-08krewox/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-08krewox/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-08krewox/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-08krewox/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).


WARNING: Discarding https://files.pythonhosted.org/packages/c7/ca/75236b17f1b951950ffc55d657c5aa408d3d0327a1b6c4c0f7cb16ef7e7b/psycopg2-2.8.tar.gz#sha256=49c5838d90e83217909db3789d30a105385b5e696ec5168cda645546c542f35a (from https://pypi.org/simple/psycopg2/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2~=2.8.0 (from versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1)
ERROR: No matching distribution found for psycopg2~=2.8.0
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.1/lib/python3.9/site-packages/riot/riot.py", line 516, in prepare
    Session.run_cmd_venv(
  File "/root/.pyenv/versions/3.9.1/lib/python3.9/site-packages/riot/riot.py", line 922, in run_cmd_venv
    return run_cmd(args, stdout=stdout, executable=executable, env=env, shell=True)
  File "/root/.pyenv/versions/3.9.1/lib/python3.9/site-packages/riot/riot.py", line 984, in run_cmd
    raise CmdFailure("Command %s failed with code %s." % (args[0], r.returncode), r)
riot.riot.CmdFailure: (CmdFailure(...), 'Command p failed with code 1.')
```

**Comment by brettlangdon** [comment]
This is probably because you are running locally on your mac.

There are no wheels for psycopg2 for macos, so it needs to install from source. Which also means it needs to have the postgres dev headers available.

Usually it works best to run any tests needing psycopg2 in the docker container :/
